### ISSUE TITLE
bin/rails:6: warning: already initialized constant APP_PATH

### ISSUE THREAD

**Issue by pdipietro** [gonzalo-bulnes/simple_token_authentication#127]
I installed the gem following the readme, but my rails s doesn't start anymore.

    pdipietro@CUC-N4J-V4-0-0:~/gsn$ rails s
    bin/rails:6: warning: already initialized constant APP_PATH
    /home/pdipietro/gsn/bin/rails:6: warning: previous definition of APP_PATH was here

If I remove the gem from the gemfile, the server starts again. Any suggestions?
I found some hints on the web, but none worked for me ;-)

**Comment by gonzalo-bulnes** [comment]
I'm closing this issue, but feel free to re-open it needed.

**Comment by joel** [comment]
You have just an error on your code or dependencies, you have to find it, should be the same of me https://github.com/gonzalo-bulnes/simple_token_authentication/pull/196 I'd this error too. Don't look too far.

**Comment by joel** [comment]
Try to open a console `bundle exec rails c`
