### ISSUE TITLE
Q: Support for multiple logins by the same user with different mobile devices? (R: Not yet, but here are some pointers!)

### ISSUE THREAD

**Issue by dmonopoly** [gonzalo-bulnes/simple_token_authentication#135]
Suppose we have this situation:

Two mobile devices 1 and 2 - e.g., iOS and Android, or two Androids, it doesn't matter - want to log in with the same user account.

2 issues:
First:
1 logs in first; a new token is generated for that user.
2 logs in second; a new token is generated again, but now 1 no longer has access because the token has changed.

Second:
Suppose 1 and 2 are both logged in and have access, but 1 logs out. Then the token is deleted, causing 2 to no longer have access.

I recently forked this repo and am looking at how to resolve these issues, focusing primarily on this file because I think the key changes need to be here: https://github.com/gonzalo-bulnes/simple_token_authentication/blob/6b8abd8210ab2d578a142a3ca11a703ebb1beb07/lib/simple_token_authentication/acts_as_token_authenticatable.rb 

One way I am thinking of doing this is to create a SessionTokens table with a User has_many SessionTokens relationship. SessionToken only has one field: authentication_token:string.
On login we create a SessionToken. On logout we remove it.

Sound good?

If this method sounds okay to you, then I have a question about the acts_as_token_authenticatable.rb file linked above: **Is before_save used only to guarantee on login to create a token as appropriate?** In this new method, do we always create a new token and no longer use a check ```if authentication_token.blank?``` That's where I'm a little confused - in the original method, why is before_save used as the hook?

**Comment by mmhan** [comment]
@dmonopoly - How's the change coming along? I'd be happy to contribute to move this along too.

**Comment by dmonopoly** [comment]
Hi @mmhan, I actually didn't get to implementing this idea - things changed in my project. But please go ahead with it if you feel it's useful! =]

**Comment by gonzalo-bulnes** [comment]
Hello @dmonopoly, @mmhan,

I think the feature would be great (I don't want to create any misunderstanding!). That being said, it's a lot of work.  While I haven't yet looked closely at it, I know that @adamniedzielski is writing a gem named [Tiddle](https://github.com/adamniedzielski/tiddle) to cover this particular use case and I think that both of you may find interesting taking a look at it.

If you do, please keep me updated on your impressions, so I can recommend it to others. I'm convinced that both gems will benefit from these shared experiences.

Best regards!

**Comment by mmhan** [comment]
@gonzalo-bulnes - That's great! First hearing of Tiddle, I will definitely give it a try.

**Comment by jamesfzhang** [comment]
I'm running into a similar situation with a web & mobile client. For instance, when logging out on web, I call `current_user.update(authentication_token: nil)`, which resets the authentication token. Consequently, this invalidates the mobile client's session. To fix this, I'm thinking about just not resetting `authentication_token` on the server side during log out, and simply just forgetting it on the client side. Would this be awful for security purposes?

**Comment by gonzalo-bulnes** [comment]
Hello @jamesfzhang,

You can't prevent users from storing their authentication token elsewhere, that's the point of resetting it. But forgetting it in the client -as long as the client really forgets it- would prevent others to use your lost phone to accede you account. That's certainly a first step.
