### ISSUE TITLE
scope authentication to subdomain

### ISSUE THREAD

**Issue by cspeer** [gonzalo-bulnes/simple_token_authentication#148]
Hi,

thanks a lot for this gem :)
In my rails application I have implemented the following strategy to bind users to a certain subdomain
https://github.com/plataformatec/devise/wiki/How-to:-Scope-login-to-subdomain

Since I would also need this functionality when signing in with a token I was wondering what your approach to this would be. Certainly you could somehow hack it into this method:
https://github.com/gonzalo-bulnes/simple_token_authentication/blob/3403a7eacc7de3d77fba0b2aa1d1e908abd7cd78/lib/simple_token_authentication/token_authentication_handler.rb#L54

But that doesn't seem quite as clean to me. So any ideas? :)

Thanks
Chris

**Comment by bradseefeld** [comment]
+1

I also scope user authentication to subdomain (which represents the organization), but I think in general, the ability to scope the user lookup by arbitrary parameters would be good.

**Comment by gonzalo-bulnes** [comment]
Hi @bradseefeld, @cspeer,

As a first approach, would modifying [the parameters that are used to find the user](https://github.com/gonzalo-bulnes/simple_token_authentication/blob/v1.7.0/lib/simple_token_authentication/token_authentication_handler.rb#L62) be enough?
```ruby
# lib/simple_token_authentication/token_authentication_handler.rb

# ...

def find_record_from_identifier(entity)
  email = entity.get_identifier_from_params_or_headers(self).presence
 
  email = integrate_with_devise_case_insensitive_keys(email)
 
  record = nil


  unless devise_subdomain_scope_enabled?
    # The finder method should be compatible with all the model adapters,
    # namely ActiveRecord and Mongoid in all their supported versions.
    record = email && entity.model.where(email: email).first
  else
    # The finder method should be compatible with all the model adapters,
    # namely ActiveRecord and Mongoid in all their supported versions.
    record = email && entity.model.where(email: email, subdomain: params[:subdomain]).first
  end
end

def devise_subdomain_scope_enabled?
   # this condition is aproximative, let's refine it later
  params[:subdomain].presence
end

# ...

```

**Comment by bradseefeld** [comment]
IMO, this would convolute the situation a bit more. The implementation makes the assumption that I have a subdomain field on the user model (I dont). My subdomain maps to an Organization and my users have an organization_id field.

I think what would make your gem much more flexible, and solve a lot of the 'feature requests' on this issue tracker related to user lookup, is if this was delegated to a strategy pattern. It would be much better if I could define the method myself, with the guarantee that I either return a single user or nil. I can extend some base class perhaps and configure which strategy class to use in my initializer.

Right now its pretty difficult to extend the functionality of the gem given that all the methods are private. I know I can monkey-patch, etc, but I really prefer not to, especially when it comes to my auth layer.

**Comment by gonzalo-bulnes** [comment]
Ok, let's refine a little and include the params that you provided when configuring Devise:

```ruby
# lib/simple_token_authentication/token_authentication_handler.rb

# ...

def find_record_from_identifier(entity)
  email = entity.get_identifier_from_params_or_headers(self).presence
 
  email = integrate_with_devise_case_insensitive_keys(email)
 
  record = nil

  unless devise_subdomain_scope_enabled?
    # The finder method should be compatible with all the model adapters,
    # namely ActiveRecord and Mongoid in all their supported versions.
    record = email && entity.model.where(email: email).first
  else
    identification_params = email && { email: email }.merge params.select {|key, _| request_keys.include? key }
    # The finder method should be compatible with all the model adapters,
    # namely ActiveRecord and Mongoid in all their supported versions.
    record = identification_params && entity.model.where(identification_params).first
  end
end

def devise_subdomain_scope_enabled?
  Devise.request_keys.any?
end

# ...

```

**Comment by bradseefeld** [comment]
That would probably get _me_ pretty close to what I need, but is this really the route you want to go? I doubt you want to maintain every single person's edge case that will ever exist. Is there a reason to avoid something like a strategy pattern?

Honestly, this still doesnt serve my need as the subdomain I am using maps to the organization, which the user belongs to. I dont use the devise subdomain stuff. I use a before hook to inject an organization_id based on the value of the subdomain. Eg., I have to do an organization lookup to get its PK ID.

I am not saying your gem should support my use case. I dont think my use case is completely fringe, but its not the majority. However, I do think gems such as yours should remain flexible as much as possible and I dont see how you can do that without allowing some aspects to be pluggable.

**Comment by gonzalo-bulnes** [comment]
I see no edge case here, I see instead a [well described use case][comment] which is based on a reference article from the Devise community, which describes a common use of the **[request_keys][keys]** Devise option. I believe common practices are worth being supported, and such documented ways to use Devise are what I think _Simple Token Authentication_ should support. @bradseefeld  Your point was clear, however, and I thank you for sharing your views.

To answer @cspeer, yes, the `find_record_from_identifier` is the right place to look, and I see no reason for the patch not to be clean as long as we make sure that:
- the method performs as expected with any valid `Devise.request_keys` value
- configuration that was set for Devise has not to be repeated for _Simple Token Authentication_

I look forward for feedback about the effectiveness of the search query. Once the principle approved, I'l write the corresponding test suite. Of course, contributions are welcome!

Regards!  : ) 

  [comment]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/148#issue-55466717
  [keys]: https://github.com/plataformatec/devise/search?utf8=%E2%9C%93&q=request_keys

**Comment by cspeer** [comment]
Well, when I think about it @bradseefeld's approach to link users to a parent entity which then relates to a certain subdomain makes much more sense, since it's a lot more maintainable when, say the subdomain name changes. But yes @gonzalo-bulnes's you are right, patching ```find_record_from_identifier``` would certainly do the trick.

However, on the long run I agree with @bradseefeld that maybe some kind of auth strategy would be nice to have. So speaking of common practices, how about making use of Devise's [find_for_authentication](http://www.rubydoc.info/github/plataformatec/devise/Devise/Models/Authenticatable/ClassMethods#find_for_authentication-instance_method) method or are you already doing that? A quick search with Github in the repo didn't turn up anything.

So thanks a lot for your answers :)

Cheers!
