### ISSUE TITLE
Devise needs to be upgraded to work with Rails 4.2

### ISSUE THREAD

**Issue by nicolo** [gonzalo-bulnes/simple_token_authentication#152]
I saw this error when trying to upgrade my application to rails 4.2. https://github.com/plataformatec/devise/issues/3158

It seems to be resolved in Devise 3.4.1 and simple_token_auth is currently configured for Devise ~> 3.2

**Comment by gonzalo-bulnes** [comment]
Hello @nicolo,

The `~> 3.2` constraint does include `3.4.1`.
It is called **pessimistic version constraint** and is equivalent to `>= 3.2` and `< 4.0` (see the [Bundler docs about Gemfiles][bundler]). Could be another condition preventing your Devise upgrade?

By the way, the _Simple Token Authentication_ build on Travis CI runs [using Devise 3.4.1][gemnasium] : )


**Note**: The pessimistic version constraints are useful when dependencies follow the [semantic versionning][semver] conventions. The semantic versionning conventions do restraint the major version changes to non-backward-compatible API/behaviour modifications and the pessimistic version constraints make easy to prevent dependencies to be upgraded in risky ways, while allowing any kind of safe upgrade.

  [bundler]: http://bundler.io/gemfile.html
  [semver]: http://semver.org/
  [gemnasium]: https://gemnasium.com/gonzalo-bulnes/simple_token_authentication

**Comment by nicolo** [comment]
@gonzalo-bulnes  You are right. My bad. I was reading it as ~>3.2.0. I'll investigate on my end.
