### ISSUE TITLE
Authentication doesn't work

### ISSUE THREAD

**Issue by giedriusr** [gonzalo-bulnes/simple_token_authentication#154]
Hello,

I am allowed to access my controller action without protection. It should throw `401`, but I get `200` instead. What's wrong? If I remove `fallback_to_devise: false`, I always get `401`.

EDIT: apparently I need to render 401 explicitly.

```ruby
# Gemfile
source 'https://rubygems.org'

gem 'rails',                         '4.2.0'
gem 'rails-api'
gem 'devise'
gem 'simple_token_authentication',   '~> 1.0'
```

```ruby
# controllers/application_controller.rb
class ApplicationController < ActionController::API
end

# controllers/api/v3/home_controller.rb
class Api::V3::HomeController < ApplicationController
  acts_as_token_authentication_handler_for User, fallback_to_devise: false

  def index
    render json: { message: 'You are successfully authenticated!' }
  end
end

```

```ruby
# routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api, defaults: { format: :json } do
    namespace :v3 do
      get '/home', to: 'home#index'
    end
  end

  match '(*path)', to: 'errors#routing', via: :all
end
```

```ruby
# models/user.rb
class User < ActiveRecord::Base
  acts_as_token_authenticatable

  devise :database_authenticatable, :lockable,
         :recoverable, :trackable, :validatable

  validates :first_name, :last_name, :email, :password, presence: true
end
```

**Comment by gonzalo-bulnes** [comment]
Hi @giedriusr,

The behaviour may be unexpected for you but it is the default behaviour: if authentication from token is successful, `current_user` will be set. If not, `current_user` won't be set.

What you do if `current_user` is not set is up to you. Responding **401 Unauthorized** (that's to say making authentication mandatory) is obviously an option.

You can do so through a little helper method:

  [demo]: https://github.com/gonzalo-bulnes/rails-api-authentication-demo/blob/master/app/controllers/home_controller.rb

```ruby
# app/controllers/home_controller.rb

class HomeController < ApplicationController
  acts_as_token_authentication_handler_for User, fallback_to_devise: false
  before_action :require_authentication! # eventually scoped to only: :restricted_action

  # ...

  private
    def require_authentication!
      throw(:warden, scope: :user) unless current_user.presence
    end
end
```

Take a look at this [Rails::API authentication demo][demo] to see this code in action!

Regards!

**Comment by giedriusr** [comment]
Hi @gonzalo-bulnes! What a nice gesture from you building an example :+1: Thanks a lot! Yeah, in the end I saw that I need to handle this on my own which is logical, pity that I didn't realize that from the very beginning (too addictive to devise default behaviour).
Closing the issue as solved!

**Comment by gonzalo-bulnes** [comment]
I'm glad that you liked the example. I've edited slightly the issue title to make it easy to find in the [FAQ][faq]. Regards!

  [faq]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues?q=label%3Aquestion+is%3Aclosed

**Comment by giedriusr** [comment]
:+1:

**Comment by gonzalo-bulnes** [comment]
Hi @giedriusr,

I released **v1.10.0** with support for a new option: `fallback: :exception` (just to make you a little bit more addict to the Devise behaviour!), see #174 for details : )

Cheers!

**Comment by giedriusr** [comment]
Awesome :+1: Great job @gonzalo-bulnes

**Comment by rmonteiro89** [comment]
`fallback: :exception` throws warden Unauthorized, but Devise capture it with the FailureApp and redirect to the root_page. In my case, I have an API and want it to respond with status 401, and not to be redirect. Any idea what I am doing wrong or what would be the solution for this?

**Comment by rmonteiro89** [comment]
I think i found a solution, in `initializers/devise.rb`:
```ruby
# optional whether you want to allow http auth via browser or not
config.http_authenticatable = false

# remove the json format
config.navigational_formats = [:"*/*", "*/*", :html] 
```

**Comment by gonzalo-bulnes** [comment]
Hi @rmonteiri89,

Exactly, I think you found it. The navigational formats are defined to determine which requests should be redirected and which ones should be responded with HTTP 401. : )

**Comment by leonardoscorza** [comment]
Hi @gonzalo-bulnes, thanks for your work in this Gem :)
Maybe you can put in the README your "require_authentication" example (I think that 
a lot of people are having the "You need to sign in or sign up before continuing" problem because don't understand this step).

Thanks :)
