### ISSUE TITLE
Retrieve the auth_token?

### ISSUE THREAD

**Issue by patricks** [gonzalo-bulnes/simple_token_authentication#156]
Hello,

I don't know if this is a dumb question, but how to I retrieve the auth_token?
I have to send username / password the first time to get the auth_token or how does this work?

I currently sign_up via a HTML View and after that I read the auth token manually from the database.
Sending user-email and user-token via the http header works after that on controllers, where acts_as_token_authentication_handler_for is set.

**Comment by gonzalo-bulnes** [comment]
Hello @patricks,

You could return the authentication token as part of the signup response, but usually it is returned as part of the sign**in** response. (That allows to [renew the token][renew] on signout - e.g. `user.authentication_token = nil; user.save` - and forbid the access to the API until the next signin.) 

You can find a detailed explanation in the following [external tutorial][tutos]: [Ruby on Rails and Android Authentication][issue]

Regards!

  [renew]: https://github.com/gonzalo-bulnes/simple_token_authentication#tokens-generation
  [tutos]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues?q=label%3A%22external+tutorial%22+label%3Aquestion+is%3Aclosed
  [issue]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/45

**Comment by gonzalo-bulnes** [comment]
Hi @patricks, did the Sjors tutorial help you?

**Comment by gonzalo-bulnes** [comment]
I'll close this issue, don't hesitate to re-open it if needed!
