### ISSUE TITLE
Cannot set custom headers

### ISSUE THREAD

**Issue by emirkin** [gonzalo-bulnes/simple_token_authentication#160]
For backward compatibility, I have to receive token via the url query string rather than via HTTP headers. Yet, when I do `request.headers['X-Entity-Token'] = params[:auth_token]`, I get `HTTP_X-Entity-Token` header instead. Apparently, that's the conventional way to name headers in Rails 4.

So, which is correct - to force-set http header to `X-Entity-Token` (any ideas on how to do it in the most clean manner?) or to patch simple_token_authentication to look for the `HTTP_`-prefixed headers as well?

**Comment by gonzalo-bulnes** [comment]
Hi @emirkin,

I think you are misstaken, and as far as I know there is no convention to prefix HTTP headers with `HTTP_` in Rails 4. That's to say you should be able to get the `X-User-Token` header with ([source][example]):

```ruby
request.headers["X-User-Token"]
# => "S0meTok3n"
```

What happens is that these headers, are stored as CGI variables whose name **is** built by prefixing the header name with `HTTP_`.

Example: when you read `request.headers["Content-Type"]`, Rails does fetch `request.env('HTTP_X_USER_TOKEN')` under the hood (note that's `env`, not `headers`).

That's true for all headers that does not correspond to [pre-defined CGI variables][cgi-vars]. (See the [following two][src_1] [methods][src_2] from `ActionDispatch::Http::Headers`, that's where everything happens.)

  [example]: http://api.rubyonrails.org/classes/ActionDispatch/Request.html#method-i-headers
  [src_1]: https://github.com/rails/rails/blob/e7b0947afdc8c9f4119d06628070667b9e7875d1/actionpack/lib/action_dispatch/http/headers.rb#L39-L42
  [src_2]: https://github.com/rails/rails/blob/e7b0947afdc8c9f4119d06628070667b9e7875d1/actionpack/lib/action_dispatch/http/headers.rb#L87-L97
  [cgi-vars]: https://github.com/rails/rails/blob/e7b0947afdc8c9f4119d06628070667b9e7875d1/actionpack/lib/action_dispatch/http/headers.rb#L9-L28

----

Anyway, _Simple Token Authentication_ can be [configured][config] to watch for custom headers through its **header_names** option:

```ruby
# config/initializers/simple_token_authentication.rb

SimpleTokenAuthentication.configure do |config|

  # Configure the name of the HTTP headers watched for authentication.
  config.header_names = { user: { authentication_token: '<any_header_you_want_for_tokens>', email: '<idem_for_emails>' } }
end
```
There is happily no need to patch anything ; )




  [config]: https://github.com/gonzalo-bulnes/simple_token_authentication#configuration

**Comment by emirkin** [comment]
Ah! I was setting `X-Entity-...` instead of `X-Account-...`. Authentication works now.

However, I still have one more problem. If I throw my method in `:except` (e.g. `before_filter :authenticate_account!, except: [:mymethod, :anothermethod]`), it still runs the authentication filter. How can I disable authentication for several methods of the same controller?
