### ISSUE TITLE
Cannot skip authentication

### ISSUE THREAD

**Issue by emirkin** [gonzalo-bulnes/simple_token_authentication#164]
If I throw my method in :except (e.g. before_filter :authenticate_account!, except: [:mymethod, :anothermethod]), it still runs the authentication filter. How can I disable authentication for several methods of the same controller?

```
class ApiController < ApplicationController
  acts_as_token_authentication_handler_for Account
  before_filter :authenticate_account!, except: [:mymethod, :anothermethod]
```

**Comment by gonzalo-bulnes** [comment]
By defaut, _Simple Token Authentication_ does fallback to the other Devise strategies when token authentication fails, yet the **fallback_to_devise** option allows to disable that fallback when necessary:

```ruby
# app/controllers/api_controller.rb

class ApiController < ApplicationController

  acts_as_token_authentication_handler_for Account, fallback_to_devise: false
  before_filter :authenticate_account!, except: [:mymethod, :anothermethod]

  # ...
end
```

See [integration with other authentication methods][doc] in the `README`.

  [doc]: https://github.com/gonzalo-bulnes/simple_token_authentication#integration-with-other-authentication-methods

**Comment by emirkin** [comment]
thank you!

**Comment by gonzalo-bulnes** [comment]
@emirkin Can I close this issue?
