### ISSUE TITLE
Several token authenticatable models > only last handler works

### ISSUE THREAD

**Issue by DrLuthor** [gonzalo-bulnes/simple_token_authentication#170]
Hi,

I'm using simple_token_authentication 1.9.0
in my app, I've got 2 models : Users and Admins.
I want to restrict the access of certain views to logged in Users or Admins.
So, I followed the indications shared in the Installation process. But I always get a 401 Unauthorized error for the first "acts_as_token_authentication_handler_for" I declared in my controller.
Which means in the following case, each time I signed in as an Admin and try to access a view of MyController, I'm redirected to the User login form -_-

Did I miss something ? Any idea ? (sorry for the format, I didn't find any wysiwyg interface :/ )

My controller :
class MyController < ApplicationController
  acts_as_token_authentication_handler_for Admin, fallback_to_devise: false
  acts_as_token_authentication_handler_for User
...
end

My classes :
class Admin < ActiveRecord::Base
  acts_as_token_authenticatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
...
end

class User < ActiveRecord::Base
  acts_as_token_authenticatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
...
end

My tables :
  create_table "admins", force: true do |t|
    t.string   "email",                  default: "", null: false
    t.string   "encrypted_password",     default: "", null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0,  null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "role",                   default: 0
    t.string   "authentication_token"
  end

  create_table "users", force: true do |t|
    t.string   "email",                  default: "", null: false
    t.string   "encrypted_password",     default: "", null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0,  null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "authentication_token"
    t.integer  "company_id"
  end

And my route
...
devise_for :admins,   :controllers => {registrations: 'admins/registrations', sessions: 'admins/sessions' }
  devise_for :users,   :controllers => {registrations: 'users/registrations' }
...

**Comment by gonzalo-bulnes** [comment]
Hello @DrLuthor,

Remember that _Simple Token Authentication_ falls back to Devise authentication strategies by default.

Try disabling the fallback for `User` (as you did for `Admin`) and then configure Devise to require authentication the way that fits your scenario.

Your issue seems very similar to #164 in fact! You'll find an example that I think you may find useful.

Regards!

**Comment by gonzalo-bulnes** [comment]
Hi @DrLuthor, did you find the answer you were looking for in #164?
