### ISSUE TITLE
Why is the token unique?

### ISSUE THREAD

**Issue by mhuggins** [gonzalo-bulnes/simple_token_authentication#178]
Authentication tokens as implemented in devise were unique because the query for authenticating a user was based upon the token alone.  This gem, however, is searching by the identifier (e.g.: email by default), which should already be unique, with the `token_correct?` method comparing tokens after the record is already in memory.

Given that, it seems that the migration instructions can be changed to remove the DB index, and the `generate_authentication_token` method could be changed to simply be:

```ruby
def generate_authentication_token(token_generator)
  token_generator.generate_token
end
```

Is there something I'm missing?  If not, I'm happy to add a pull request.

**Comment by gonzalo-bulnes** [comment]
Hello @mhuggins,

Authentication tokens are not _required_ to be unique. However, the rarer authentication tokens are, the more secure they are. (To put an extreme example, if all your users did use the same authentication token, then obtaining an authentication token from a single user would allow an attaker to impersonate any of them.)

Ensuring authentication tokens are unique then is a simple way to make sure they are rare enough.
The database index, in turn, is a way to reflect that constraint in the database.

Regards!
