### ISSUE TITLE
Add to testing documentation how to set auth headers 

### ISSUE THREAD

**Issue by johnmosesman** [gonzalo-bulnes/simple_token_authentication#179]
Hi there,

Can we add some documentation on how to set the request headers for minitest/rspec? It took me a while to figure out how to add the headers for testing, and it could save other people a lot of time to add it to the documentation.

I tried many variations that have been successful with other systems in the past (like setting `@request.env['blah']`) until I found the `@request.headers['X-User-Email']`.

I can make a PR for the docs change if you'd like.

Thanks!

**Comment by gonzalo-bulnes** [comment]
Hi @johnmosesman,

Please do, such a PR would be very welcome!
For a short explanation I think a **Usage > Testing** section could be a good idea. If you want to write something longer with a few examples, you can also add a whole file into the `doc/` directory, with a link in the `README`. What do you think? : )

**Comment by johnmosesman** [comment]
I think some basic examples (query vs headers) in the README would be great. I'll submit a PR!

**Comment by gonzalo-bulnes** [comment]
Totally cool!
