### ISSUE TITLE
Q: Optional authentication (R: Use the fallback option or a custom lambda!)

### ISSUE THREAD

**Issue by mib32** [gonzalo-bulnes/simple_token_authentication#183]
Devise is constructed in way, that you can access any page (unless you set `before_filter :authenticate_user!`) whether or not you are logged in - the only difference that the `current_user` will be either `nil` or you. 
I would really like to achieve the same behaviour from this gem. Now - if i set some controller as token authentication handler, it prevents access if no token is passed.

**Comment by mib32** [comment]
Ok, i got this in a minute later, sorry:
```ruby
class BusinessesController < ApplicationController
  acts_as_token_authentication_handler_for User, if: lambda { |controller| controller.params["authentication_token"].present? }
end
```

**Comment by gonzalo-bulnes** [comment]
Hi @mib32,

By default, when token authentication fails (user credentials were missing or incorrect), _Simple Token Authentication_ falls back to Devise - that's to say invokes `authenticate_user!`. You can modify that behaviour through the **fallback** option:

```ruby
# app/controllers/business_controller.rb

class BusinessesController < ApplicationController
  acts_as_token_authentication_handler_for User, fallback: :none
end
```

**Comment by gonzalo-bulnes** [comment]
@mib32 Taking a second look: if you want your users to be able to access a page despite they provided incorrect credentials, then you want defintely to disable the Devise fallback!

**Comment by mib32** [comment]
@gonzalo-bulnes Thanks :+1: .
