### ISSUE TITLE
Devise json new session with email and password?

### ISSUE THREAD

**Issue by ademgashi** [gonzalo-bulnes/simple_token_authentication#185]
Hi @gonzalo-bulnes , i hope you are well with everything.
Is this scenario doable with this gem.
Consider a mobile app that sends the user and password to devise new sessions and gets back the token?

**Comment by gonzalo-bulnes** [comment]
Hi @ademhashi,

Yes, that's how it works indeed. The first contact with the API consists in obtaining the user authentication token. To do so, you send the user's email and password to the usual Devise endpoint (and you modify its response to include the user _authentication token_, tjat may be JSON or anything else your mobile app can work with). The mobile app stores the authentication token it received and includes it in every posterior request to the API, along with the user's email. (Her password was only used once and doesn't need to -shouldn't- be stored by the mobile app.)

If at any moment you want to force the mobile app to provide the user password again, all you have to do is renewing the _authentication token_ server-side. The app will no longer be able to acceed to the API endpoint with the user's email and the obsolete authentication token, and will be "forced" to ask the user her password to start the process again and get the new authentication token.

Note that the _Simple Token Authentication_ role consists in managing the users' authentication tokens, and providing ways for the controllers to enforce access control using these tokens. The mecanism through which your mobile app gets the user's authentication token initially is the Devise's part of the job.

Cheers!

**Comment by ademgashi** [comment]
Thank you very much for the response.
