### ISSUE TITLE
iOS “Bookmark to Homescreen”

### ISSUE THREAD

**Issue by karlingen** [gonzalo-bulnes/simple_token_authentication#189]
I opened an issue at devise repo: https://github.com/plataformatec/devise/issues/3709 but they closed it. 
Can I somehow fix this issue with this gem?

**Comment by gonzalo-bulnes** [comment]
Hello @karlingen,

I'm not very familiar with the "Bookmark to Homescreen" feature on iOS, but provided it works as a regular bookmark, and as long as the link you bookmarked contains valid authentication credentials, then you may be able to use it as you intend. But that's much of a workaround and does not solve the issue at all.

Why?
An user who would sign in, then save a bookmark to her home screen, would be able to open her bookmark later and be signed in. That's true. But suppose that she later signs out (usually authentication tokens are expected to be renewed on signout), then her bookmark would no longer sign her in automatically, and you'd back to your original problem. The only way for your user to get the feature again would be to remove, then create the bookmark again, and from that point of view, the solution is very inferior to the usual session maintained by Safari.

I don't think that's an uncommon issue however, and I think the J. Valim's advice was quite good: the Devise or iOS communities on [StackOverflow](https://stackoverflow.com/questions/tagged/devise) may be able help further.

Keep me updated with your findings!
Regards,

**Comment by karlingen** [comment]
@gonzalo-bulnes Oh yeah, you are right. 
I guess storing the token in localStorage and fetching it on login is the only solution then.

Thanks a bunch for your input.
