### ISSUE TITLE
Question: how to expire the token after a successful sign in ?

### ISSUE THREAD

**Issue by feliperaul** [gonzalo-bulnes/simple_token_authentication#199]
Hi everyone

@gonzalo-bulnes, first of all, this gem is amazing :)

My use case requires setting ```  # config.sign_in_token``` to ```true```, but I wish that after a successful sign in, the token changed, rendering the old one invalid. Maybe this could be set as a new option in the config ?

Here is the use case: I want to send the user a transactional email inviting them to do some action in my app. When they click the link in that e-mail, they are signed in automatically and session is persisted (they are kept signed in until they log out). But after this click in the e-mail link, I want the token to expire, so if the user clicks again on the same email link, it will ask for credentials (if he's logged out of course). 

How do I flag this as a question and not an issue ?

**Comment by gonzalo-bulnes** [comment]
Hi @feliperaul,

In your **sign in** action, just [reset the user's authentication token][doc] and the link won't sign her in anymore. Because your session was persisted, your user will still be signed in until she signs out,  and the will still take her to the correct page.

  [doc]: https://github.com/gonzalo-bulnes/simple_token_authentication#tokens-generation

Building on the same scenario we defined in #163:

```ruby
# config/initializers/simple_token_authentication.rb

SimpleTokenAuthentication.configure do |config|

  # Configure the session persistence policy after a successful sign in.
  config.sign_in_token = true

end
```

```ruby
# app/models/user.rb

class User < ActiveModel
  acts_as_token_authenticatable

  # Invalidate the user's authentication token and set a new one
  #
  # user - a token authenticatable User
  #
  # Returns the user's new authentication token
  def reset_authentication_token!
      authentication_token = nil
      save # automatically generates a new authentication token
      authentication_token 
  end

  # ...

end
```

```ruby
# app/controllers/susbscriptions_controller.rb

class SubscriptionsController < ActionController

  # the first time users' credential are present and correct they will get signed in
  acts_as_token_authentication_handler_for User

  def renew
    # do whatever you need to renew the user's subscrption
    current_user.reset_authentication_token!
    # then build the response as usual

    # ...
  end

  # ...

end
```

Do not worry about issues being issues or issues being questions or whatever. Issues are meant to communicate and they just appear to have a scary name. Please open as many as you need to keep topics distinct, I'll take care of labelling them so they're easy to find. ; )

**Comment by feliperaul** [comment]
@gonzalo-bulnes Thanks for the amazing support, really fast and helpful !

Gonzalo, what if I wanted to run ```current_user.reset_authentication_token!``` after every sign_in that used a token, no matter what controller was being triggered ?

In other words: how to expire the token right after sign_in, regardless of the controller/action I'm sending the user to ?

**Comment by gonzalo-bulnes** [comment]
That's a good question! You could override the [`SimpleTokenAuthentication::SignInHandler#sign_in`][src] method to reset the `user` (a.k.a `record` in the scope of the method) authentication token.

Something like this:

```ruby
module SimpleTokenAuthentication
  class SignInHandler
    # Devise sign in is performed through a controller
    # which includes Devise::Controllers::SignInOut
    def sign_in(controller, record, *args)
      integrate_with_devise_trackable!(controller)

      controller.send(:sign_in, record, *args)
      record.reset_authentication_token! # look here!
    end

    private
      # ... unchanged
  end
end
```

Implementing a hook there could be a good idea indeed, I'll think about it.

  [src]: https://github.com/gonzalo-bulnes/simple_token_authentication/blob/v1.10.1/lib/simple_token_authentication/sign_in_handler.rb#L3-L9

**Comment by ianchen06** [comment]
@gonzalo-bulnes Hi, thanks for the great gem.

I cannot seem to get the above monkey patch to work as the method is never called in my application.

I think I don't quite understand the logic of this gem and how it hooks with Devise I guess.

my `sign_in` method of the `SingnInHandler` in simeple_token_auth was never called(I tried to insert `puts` statements in every function but none of them gets called,

I apologize if I'm missing something really basic, I've been stuck on this one for days..

Thanks for your great work :)

**Comment by gonzalo-bulnes** [comment]
Hi everyone,

An `after_successful_token_authentication` hook (callback) has been introduced in **v1.15.0**, which fits exactly this scenario (see the [the Hooks section of the `README`][doc]).

The `renew_authentication_token` helper could be something in the lines of:

```ruby
# app/controllers/application_controller.rb

# ...

private

  def renew_authentication_token!
    current_user.authentication_token = nil
    current_user.save!
  end
```

Please provide any feedback related to this feature in #217 : )
  

  [doc]: https://github.com/gonzalo-bulnes/simple_token_authentication/tree/v1.15.0#hooks
