### ISSUE TITLE
Question: how to initialize authentication_token for all users ?

### ISSUE THREAD

**Issue by feliperaul** [gonzalo-bulnes/simple_token_authentication#200]
After following the gem documentation, I get a column in my db named authentication_token, with all rows set to null.

How do I initialize them ?

**Comment by gonzalo-bulnes** [comment]
Hi @feliperaul,

The authentication tokens are [generated automatically when you `save` the token authenticatable record][doc] - say `user`). If you want to initialize them all at once (before a mailing campaign for example, I'm thinking in the #163, #199 scenario), you may find useful to define a Rake task to do it:

```ruby
#lib/tasks/initialize_users_authentication_tokens.rake

require 'rake'

namespace :users do
  desc "Ensure all users have an authentication token, preserve existing ones"
  task initialize_authentication_tokens: :environment do
    User.all.each { |user| user.save if user.authentication_token.blank?  }
  end
end
```

  [doc]: https://github.com/gonzalo-bulnes/simple_token_authentication#tokens-generation

**Comment by feliperaul** [comment]
@gonzalo-bulnes Thanks, this is amazing.
