### ISSUE TITLE
Handle  Token in an Android app

### ISSUE THREAD

**Issue by RicardoUnorte** [gonzalo-bulnes/simple_token_authentication#203]
Hello there! actually i have my rails app with devise and I use theis gem to secure it. So my question is how to hanlde or get the token for make request to the API in rails in an Android app that i an developing. An example could help me more thanks a lot!

**Comment by gonzalo-bulnes** [comment]
Hi @RicardoUnorte,

Usually, you'll include the _authentication token_ in the response to a successful signin, see #156.
See also this **[tutorial][announce]** for a step by step explanation.

Regards!

  [announce]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/45#issuecomment-38810391

**Comment by RicardoUnorte** [comment]
@gonzalo-bulnes Hi Gonzalo and thanks for answering but it seems the tutorial no longer available :(

**Comment by gonzalo-bulnes** [comment]
I was pointing you to the **Sjors**' comment where both a _blog post_ and an _example project_ are announced. (Both links seem right to me... let me know if you can't reach them.)

**Comment by RicardoUnorte** [comment]
Yeah both links are up, sorry and thanks for the help again i will take a look of them.

**Comment by karlingen** [comment]
Here is the solution that I came up with. It also makes sure that it does not create a bunch of sessions for json requests

```ruby
# app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  skip_before_action :verify_authenticity_token
  before_action :skip_session

  respond_to :json

private

  def skip_session
    return unless json_request?
    request.session_options[:skip] = true
  end

  def json_request?
    request.format.json?
  end
end
```

Modify your routes file:
```ruby
# config/routes.rb
...
devise_for :users, controllers: { sessions: "users/sessions" }
...
```

Now, you can simply post to your sign_in with your user's email and password and it will return user information along with `authentication_token`. Store the token in your iOS / Android app and use it when communicating with the rest of the API.

**Comment by gonzalo-bulnes** [comment]
Thank you @karlingen!

**Comment by karlingen** [comment]
@gonzalo-bulnes No, thank YOU for this awesome gem!
