### ISSUE TITLE
User doesn't stay logged in via omniauth

### ISSUE THREAD

**Issue by jamesfzhang** [gonzalo-bulnes/simple_token_authentication#218]
I added this gem and it worked great when logging in via email & password. However, I'm running into a problem with staying logged in after omniauth authentication. After being redirected to the home page after connecting via omniauth, I send an AJAX request to check whether or not a `current_user` exists, and surely it's `nil`. Any ideas?

**Comment by gonzalo-bulnes** [comment]
Hello @jamesfzhang,

At first sight, I don't think that Omniauth sessions persitence is related to _Simple Token Authentication_. Could you elaborate a little please? What makes you think they could be related?

**Comment by jamesfzhang** [comment]
Thanks @gonzalo-bulnes for your quick response. I ended up fixing the problem. I wasn't saving the user's authentication_token after the omniauth redirect. Thank you!
