### ISSUE TITLE
fallback: :exception how to use?

### ISSUE THREAD

**Issue by pashtetbezd** [gonzalo-bulnes/simple_token_authentication#219]
Is there examples? 

I have some troubles. In my case 
`      

      class Api::V1::SessionsController < Devise::SessionsController
          acts_as_token_authentication_handler_for User, only: [:destroy], fallback: :exception
          skip_before_filter :verify_authenticity_token, if: :json_request?
            skip_before_filter :verify_signed_out_user, only: :destroy
           
            def create
                warden.authenticate!(:scope => resource_name)
                render :status => 200,
                :json => { :success => true,
                    :info => "Logged in",
                    :data => { :auth_token => current_user.authentication_token } }
            end
            
            def destroy
                if user_signed_in?
                    current_user.update authentication_token: nil
                    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
                    render :status => 200,
                    :json => { :success => true,
                        :info => "Logged out",
                        :data => {} }
                else
                render :status => 200,
                :json => { :success => false,
                    :info => "Failed to log out. User must be logged in.",
                    :data => {} }
                end

            end
            
            def json_request?
                request.format.json?
            end

        end`

i have no difference between 

`acts_as_token_authentication_handler_for User, only: [:destroy], fallback: :exception`
`acts_as_token_authentication_handler_for User, only: [:destroy], fallback_to_devise: true`
or 
`acts_as_token_authentication_handler_for User, only: [:destroy], fallback_to_devise: false`

I do request without auth params
`curl -v -H 'Accept: application/json' -X DELETE http://localhost:3000/api/v1/logout`

and get same response for all cases
`{"success":false,"info":"Failed to log out. User must be logged in.","data":{}}`

**Comment by gonzalo-bulnes** [comment]
Hi @pashtetbezd, the #227 issue made me think of yours, did you try skipping `:verify_signed_out_user` **before** defining the token authentication-related callbacks?

```ruby
skip_before_filter :verify_signed_out_user, only: :destroy
skip_before_filter :verify_authenticity_token, if: :json_request? # moving this one might not be necessary
acts_as_token_authentication_handler_for User, only: [:destroy], fallback: :exception
```

I think it really time to create a [Troubleshoorting section in the wiki](https://github.com/gonzalo-bulnes/simple_token_authentication/issues/233#issuecomment-206094531)!
