### ISSUE TITLE
Testing with RSpec: "Undefined method `authenticate?' for nil:NilClass"

### ISSUE THREAD

**Issue by om-nishu-trantor** [gonzalo-bulnes/simple_token_authentication#220]
Hi,
I have introduced this gem recently on `user` model and trying to test it but getting errors after errors, so thought to raise an issue here.

```ruby
require 'rails_helper'

RSpec.describe SessionsController, type: :controller do

  describe "POST /sessions" do

    before :each do
      @request.env["devise.mapping"] = Devise.mappings[:user]
      @user = create(:user, password: 'password123', password_confirmation: 'password123')
      @user.skip_confirmation!
    end

    it 'should 401 if bad credentials' do

      post :create, 
      { user: {email: @user.email, password: @user.password} }.to_json, 
      format: :json

      puts response.body
      expect(response.response_code).to eq 401

    end

  end

end
```

in the `rails_helper` there is a file called `spec_helper` which includes required Devise modules for testing i.e.

`rails_helper` :-

```ruby
ENV['RAILS_ENV'] ||= 'test'
require 'spec_helper'
require File.expand_path('../../config/environment', __FILE__)
require 'rspec/rails'
require 'pundit/rspec'

ActiveRecord::Migration.maintain_test_schema!

RSpec.configure do |config|

  config.fixture_path = "#{::Rails.root}/spec/fixtures"
  config.use_transactional_fixtures = false
  config.infer_spec_type_from_file_location!
  config.before(:each) do
    set_selenium_window_size(1300, 900) if Capybara.current_driver == :selenium
  end
end

```

`spec_helper` :-
```ruby
#check below for configuration settings
#http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'database_cleaner'
require 'factory_girl_rails'
require 'support/capybara'
require 'warden'
require 'devise'

RSpec.configure do |config|
  config.include Warden::Test::Helpers
  config.include Devise::TestHelpers, :type => :controller
  config.include Capybara::DSL

  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.before(:each) do
    DatabaseCleaner.clean_with(:truncation)
  end

  config.before(:suite) do
    begin
      DatabaseCleaner.strategy = :transaction
      DatabaseCleaner.start
      # FactoryGirl.lint
    ensure
      DatabaseCleaner.clean
    end
  end

  config.before :suite do
    Warden.test_mode!
  end

  config.include FactoryGirl::Syntax::Methods
end

```

following line added in my `routes.rb` file :-

```ruby
devise_for :users, 
  :controllers => 
  {
    :omniauth_callbacks => "omniauth_callbacks", 
    :registrations => 'registrations', 
    :invitations =>  'invitations', 
    :sessions => 'sessions'
  }
```

and initializer `simple_token_authentication.rb` contains :-

```ruby
SimpleTokenAuthentication.configure do |config|
  config.sign_in_token = false
end
```

I am still getting failure while testing the above test case
```bash
Failures:

  1) SessionsController POST /sessions should 401 if bad credentials
     Failure/Error: post :create,
     NoMethodError:
       undefined method `authenticate?' for nil:NilClass
```

**Comment by gonzalo-bulnes** [comment]
Hello @om-nishu-trantor,

This issue seems to be related to Warden. (See [this Devise issue][devise] and the corresponding [Warden issue][warden].)

Could you be using Warden **v1.2.5**? (You can check that by looking at the `GEM` section of your `Gemfile.lock`.)
If so, running `bundle update warden` should do the trick.

Keep me updated!

  [devise]: https://github.com/plataformatec/devise/issues/3923#issuecomment-177355022
  [warden]: https://github.com/hassox/warden/issues/128#issuecomment-177266346

**Comment by om-nishu-trantor** [comment]
@gonzalo-bulnes I am using **warden (1.2.3)**
Should I be using a higher version for this ?

**Comment by om-nishu-trantor** [comment]
This issue can be resolved following 
https://github.com/plataformatec/devise/wiki/How-To:-Stub-authentication-in-controller-specs

But after that, another issue starts falling in i.e.

```bash
Failure/Error: post :create, { user: {email: @user.email, password: @user.password} }.to_json, format: :json
     NoMethodError:
       undefined method `user' for nil:NilClass
     # /home/myuser/.rvm/gems/ruby-2.2.2@gemsetname/gems/devise-3.5.2/app/controllers/devise_controller.rb:108:in `require_no_authentication'
```

Which is due to `request.env['warden']` returning nil.
It can be fixed using : 
```ruby
warden.set_user @user
```
where `@user` is an instance of User Model using Devise.

@gonzalo-bulnes, I guess, we should have an example using Rspec also in the documentation...
Shall I be creating a new issue for that ?

**Comment by gonzalo-bulnes** [comment]
Hi @om-nishu-trantor!

Many thanks for sharing this! You're right, an RSpec example would be very good to have in the documentation. Now there will be two examples (RSpec and Minitest), I think that testing examples deserve their own place in the [wiki][wiki].

I just created [a dedicated page][testing] with the Minitest example from the `README`. If you want to add an RSpec section, please go ahead. (Don't forget to fill in the _edit message_ at the bottom of the form, to keep the [page history][history] readable.)
And if you want to send a PR to replace the Minitest example by a pointer to the wiki in the `README`, I'll include your contribution in the next release.

  [wiki]: https://github.com/gonzalo-bulnes/simple_token_authentication/wiki
  [testing]: https://github.com/gonzalo-bulnes/simple_token_authentication/wiki/Testing
  [history]: https://github.com/gonzalo-bulnes/simple_token_authentication/wiki/Testing/_history

**Comment by om-nishu-trantor** [comment]
:+1:  I'll be doing that with a PR :)

**Comment by om-nishu-trantor** [comment]
Updated here :- 
https://github.com/gonzalo-bulnes/simple_token_authentication/wiki/Testing

**Comment by gonzalo-bulnes** [comment]
Cool, feel free to update it if you add specs to your test suite : )
I'll close this issue by the way, thank you again for sharing your findings!
