### ISSUE TITLE
rails 5 support?

### ISSUE THREAD

**Issue by u007** [gonzalo-bulnes/simple_token_authentication#221]
via devise 4.0 will be great :)

**Comment by chrisvel** [comment]
https://github.com/gonzalo-bulnes/simple_token_authentication/issues/214

**Comment by chrisvel** [comment]
TBH I've tried everything and this gem causes lots of errors. Magically If commented out and bundle updated, the errors dissappear. Its a pity because it's a nice to have gem.

**Comment by gonzalo-bulnes** [comment]
Hi @u007, #214 is the right place to check for progress in Rails 5 support. (Keeping all the related comments in a single issue helps keeping everyone interested in the loop.) I'll continue there.
