### ISSUE TITLE
Browser login through devise lands to `/users.json` or other js paths

### ISSUE THREAD

**Issue by om-nishu-trantor** [gonzalo-bulnes/simple_token_authentication#222]
Hi,

After implementing `simple_token_authentication` I find users redirecting to `/users.json`.
Digging a bit deeper, it receives this value from `stored_location_for(resource_or_scope)` in devise' `helpers.rb`. I am not quite sure if its coming from Devise::Mapping.

My application is not just an API application hence I've overrided the devise's sessions_controller in a way to respond to both `:html` and `:json`(given below)
```ruby
class SessionsController < Devise::SessionsController
  respond_to :html, :json

  # POST /resource/sign_in
  def create
    respond_to do |format|
      format.html { 
        super
      }
      format.json {
        warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#failure")
        render :json => { :status => :ok, :authentication_token => current_user.authentication_token }
      }
    end
  end

  def failure
    render :json => { :success => false, :error => t('devise.failure.invalid') }, status: :unauthorized
  end

end
```

Also made changes in `devise.rb`

```ruby
config.navigational_formats = ["*/*", :html, :json]
```

**Comment by gonzalo-bulnes** [comment]
Hello @om-nishu-trantor,

The [tutorial][tutorial] mentionned in #45 provides an example application which you can use as a reference when writting your sessions controller.

  [tutorial]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/45#issuecomment-38810391

**Comment by om-nishu-trantor** [comment]
It looks like we need to change that a bit.
`config.navigational_formats = ["*/*", :html, :json]`
should remain `config.navigational_formats = ["*/*", :html]`
and 
No need to have ` respond_to :html, :json` in `SessionsController`
Let me work a bit on it, to conclude the answer.
