### ISSUE TITLE
Cannot seem to get logout to work

### ISSUE THREAD

**Issue by wjdhamilton** [gonzalo-bulnes/simple_token_authentication#224]
I think that this may be related to #34 , but when I create a new user, and log him in, and then call `delete` on `users/new/sign_out` and then try and access a protected resource with that user's eMail and token, I can still access the resource. Is this normal behaviour? Have I become confused? Should logging out delete the token on the client thereby forcing the user to log in again when that device is used? Or do I have a bug?

Any thoughts would be appreciated!

**Comment by gonzalo-bulnes** [comment]
Hello @wjdhamilton,

Yes, it is normal behaviour. Please see #129.

**Comment by wjdhamilton** [comment]
Ah! OK. That actually makes a lot of sense. Thanks for the help :+1:

**Comment by gonzalo-bulnes** [comment]
Good, I'm glad it does. : )
