### ISSUE TITLE
 multiple locales for an error response

### ISSUE THREAD

**Issue by MarsonV** [gonzalo-bulnes/simple_token_authentication#230]
good afternoon! I apologize in advance for my English, I use a translator. I also want to thank @gonzalo-bulnes for this wonderful tool, it greatly helped me to develop. I have a question about the possibility to change the text of the response in the error message. For example, now I have the answer: 
`{
   "Errors": {
     "Email": [
       "Has already been taken"
     ]
   }
}`
Can I change "has already been taken" in my text? I not found anywhere information on this subject

**Comment by gonzalo-bulnes** [comment]
Hello @MarsonV,

_Simple Token Authentication_ does not provide messages by itself. The messages you get are likely provided by Devise, and you should be able to localize using YAML files. See the [i18n (internationalization) wiki page][i18n] for details and [this configuration file][found] for the example you quoted. Defining the same structure in your own YAML file should be enough:

```ruby
# fr.yml

fr:
  devise:
    failure:
      user:
        does_not_exist: "L'utilisateur %{name} n'existe pas"
  errors:
    messages:
      taken: "n'est pas disponible"
      # ...      
```

  [i18n]: https://github.com/plataformatec/devise/wiki/I18n
  [found]: https://github.com/plataformatec/devise/blob/v3.5.6/test/support/locale/en.yml

**Comment by MarsonV** [comment]
many thanks!
