### ISSUE TITLE
Mongoid 6 will be required for Rails 5 support. I need help checking what it means for Simple Token Authentication

### ISSUE THREAD

**Issue by gonzalo-bulnes** [gonzalo-bulnes/simple_token_authentication#231]
**As a** gem maintainer who is not really familar with Mongoid 
**In order to** know if I can support Mongoid 6 
**And** if I need to take specific precauutions doing so 
**I would really appreciate** some help!
**And** I would suggest anyone interested in helping to leave a comment here 
**And** to take a look at #198 : )

**Comment by gonzalo-bulnes** [comment]
About Rails 5 support, see also #214

**Comment by jblac** [comment]
Right now with Rails 5 beta4, and Mongoid from master, only thing I see is:

Module#qualified_const_defined? deprecated in favor of Module#const_defined? which will be removed in 5.1

`DEPRECATION WARNING: Module#qualified_const_defined? is deprecated in favour of the builtin Module#const_defined? and will be removed in Rails 5.1. (called from adapter_dependency_fulfilled? at /Users/jblac/.rvm/gems/ruby-2.3.0/bundler/gems/simple_token_authentication-7cca58547417/lib/simple_token_authentication.rb:49)`

Other than that, there are no errors other than that it's not adding a token to the user model ( at least in my test spec )

**Comment by gonzalo-bulnes** [comment]
Awesome @jblac

The `master` branch of Mongoid [seems to be part of the **5.x.x** series](https://github.com/mongodb/mongoid/tree/7c2ff52a0c5292b8e6bf3a9a29bbb19abae3dd5f), but the last commit was tested with Rails 5RC1 with [no issues](https://travis-ci.org/mongodb/mongoid/builds/128697921) (except for older versions of MongoDB). That sounds good : )

I'm [taking care of the warning](https://github.com/gonzalo-bulnes/simple_token_authentication/commit/f604657346195e34299f822ceb3902e7a22c1606) (and a few others) as part of the Rails 5 support, and thanks to you I'll be able to document properly the Mongoid 6 support when it's out. (Besides, I believe your feedback is enough to close #198 immediately.)

Thank you!

**Comment by jblac** [comment]
master branch of Mongoid is a 6.x.x series, as of 5.1.3 it doesn't hold support for Rails 5 afaik.

This can be evidenced by my bundle install log:
`Using mongoid 6.0.0 from git://github.com/mongodb/mongoid.git (at master@7c2ff52)`

**Comment by gonzalo-bulnes** [comment]
Oh, OK, I misinterpreted the last tag. Anyway, I think the observation still holds for Mongoid 5. Also, I confirm I'll include Mongoid when releasing the Rails 5 support.

Thank you for the precision!

**Comment by adityamajeti** [comment]
I'm using   
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'mongoid', git: 'https://github.com/mongodb/mongoid.git'
gem 'doorkeeper'(4.2.0)
gem "doorkeeper-mongodb", github: "doorkeeper-gem/doorkeeper-mongodb"

while getting an access_token i'm getting error   Mongoid.raise_not_found_error configuration option to false
 
if i use doorkeeper gem 4.0.0.rc1  i'm getting access_token

**Comment by gonzalo-bulnes** [comment]
Hello @adityamajeti,

I may be missing something, but... how is _Simple Token Authentication_ involved in your setup?

[This article in the wiki][wiki] describes which information is usually required to perform troubleshooting on a regular _Simple Token Authentication_ setup. I believe the article may help you make clearer in which way you think the issue could be related to this gem. : )

Also, since your issue seems to be specifically related to the use of _Doorkeeper_, I would suggest opening a separate issue if relevant. (This one was meant to hold the conversations about Rails 5 support to the extent it was related to the Mongoid 6 gem availablilty.)

  [wiki]: https://github.com/gonzalo-bulnes/simple_token_authentication/wiki/Asking-for-help
