### ISSUE TITLE
current_user is nil

### ISSUE THREAD

**Issue by FarihulR** [gonzalo-bulnes/simple_token_authentication#232]
I keep getting, {"error":"You need to sign in or sign up before continuing."}
```
`class Api::V1::MomentsController < ApplicationController
  skip_before_filter :verify_authenticity_token,
                     :if => Proc.new { |c| c.request.format == 'application/json' }
 
  acts_as_token_authentication_handler_for User, fallback: :devise  

  def index
    @moments = current_user.moments
  end

  def create
    @moment = current_user.moments.build(params[:moment])  
    if @moment.save
       @moment
    else
      render :status => :unprocessable_entity,
             :json => { :success => false,
                        :info => @moment.errors,
                        :data => {} }
    end
  end
end`
```
Can anyone see what is wrong with my code? 
Why  current_user is nil ?

**Comment by gonzalo-bulnes** [comment]
Hello @FarihulR,

Is [any Devise callback][ref] set in your `ApplicationController`? What is the request you are performing? Did you check [the FAQ][faq]?

  [ref]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/227#issuecomment-189869156
  [faq]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/86

Regards!

**Comment by FarihulR** [comment]
Here is `ApplicationController`

```
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token

end

```

**Comment by gonzalo-bulnes** [comment]
Hi @FarihulR,

And what's the request you're performing? It should look (depending on your routing rules) like:
```
GET https://secure.example.com/?user_email=alice@example.com&user_token=1G8_s7P-V-4MGojaKD7a
```

**Comment by gonzalo-bulnes** [comment]
@FarihulR I documented the information needed for troubleshooting in the wiki. Please see [**Asking for help**](https://github.com/gonzalo-bulnes/simple_token_authentication/wiki/Asking-for-help) for examples. : )
