### ISSUE TITLE
making one action in controller use token authentication

### ISSUE THREAD

**Issue by ror6ax** [gonzalo-bulnes/simple_token_authentication#233]
Hi, thanks for this amazing gem and all the work!

Could you kindly point what am I doing wrong here?
Before starting to sue token_auth I need to make one action not authenticable by Devise.

```skip_before_filter :authenticate_user!, only: [:api, :do_stuff]```

But when I request both methods I still get  {"error":"You need to sign in or sign up before continuing."}.
Looks like skip method does not work somehow. Any help would be tremendously useful, thnx!

**Comment by ror6ax** [comment]
Strangely, it's including acts_as_token_authentication_handler_for that causes this error...

**Comment by gonzalo-bulnes** [comment]
Hello @ror6ax!

This [comment][comment] provides a list of the basic information I need to get an idea of what can be going wrong. (Please note that knowing which options you're using when enabling the controller to _act as a token authentication handler_ was already provided in that issue, but is necessary too!)

_(I take note that the wiki is probably missing a_ **Troubleshooting** _section.)_

Could you please check that and post the answers here?

  [comment]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/232#issuecomment-195950670

**Comment by gonzalo-bulnes** [comment]
@ror6ax To make things easier, I documented the information needed for troubleshooting in the wiki. Please see [**Asking for help**](https://github.com/gonzalo-bulnes/simple_token_authentication/wiki/Asking-for-help) for examples. : )

**Comment by gonzalo-bulnes** [comment]
See also [Unexpected HTTP 401 Errors](https://github.com/gonzalo-bulnes/simple_token_authentication/wiki/Unexpected-HTTP-401-Errors)!
