### ISSUE TITLE
Empty response on login

### ISSUE THREAD

**Issue by MarkMT** [gonzalo-bulnes/simple_token_authentication#235]
I'm trying to use s_t_a with ember_simple_auth and Rails 5 api + devise. If I login with incorrect credentials I get a json response `{"error":"Invalid email or password."}` as expected. However if I submit correct credentials I get a 200 response from the server, but the response is empty.

Following [this comment](https://github.com/gonzalo-bulnes/simple_token_authentication/issues/132#issuecomment-65657917) I've added

```
  include ActionController::MimeResponds
  include ActionController::ImplicitRender

  respond_to :json
```
to my ApplicationController.

Because my front end is Ember, I'm also using ActiveModelSerializer's json_api adapter. When I log in (in development mode) I see this in my server console -
```
[active_model_serializers] Rendered PersonSerializer with ActiveModelSerializers::Adapter::JsonApi (3.08ms)
```

yet I still see nothing in the body of the response received by the browser.

As suggested in [this comment](https://github.com/gonzalo-bulnes/simple_token_authentication/issues/132#issuecomment-64966470) I've also tried overriding `Devise::SessionsController#create` to render json directly - this seems to bypass the AMS serialization, but again there's no content in the response received by the browser.

Any advice would be greatly appreciated.

**Comment by MarkMT** [comment]
Update: It seems that ActiveModelSerializers is the culprit here. If I remove it completely everything works fine as far as ember_simple_auth is concerned. Of course that's not a solution since I need the json-api serialization for my ember-data models.

**Comment by gonzalo-bulnes** [comment]
Hello @MarkMT,

You were faster than me, yes you [have to include the `authentication_token` in your API response][ref] if you want to use it. I guess including it in your `PersonSerializer` wouldn't be a good idea, but I wonder if it is possible to append it in the context of the sign in action (?) maybe not.

I would be interested in your experience using the gem with Ember, if you want to put a short example in a gist or something alike, I would be glad to put a link in the [wiki][wiki] : )

  [ref]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/203#issuecomment-158579163
  [wiki]: https://github.com/gonzalo-bulnes/simple_token_authentication/wiki

**Comment by MarkMT** [comment]
Sure, I'm on a tight schedule atm, but when I get done with this project I'll try to put something together.

**Comment by gonzalo-bulnes** [comment]
I think I can close this, right? Don't hesitate to re-open it if not.

**Comment by MarkMT** [comment]
Thanks, all good.
