### ISSUE TITLE
env is deprecated in Rails 5.1

### ISSUE THREAD

**Issue by fighterii** [gonzalo-bulnes/simple_token_authentication#237]
I'm currently using `gem 'simple_token_authentication', git: 'https://github.com/gonzalo-bulnes/simple_token_authentication.git', branch: 'spike-add-rails-5-support-without-backward-compatibility-breakage',` on my rails 5 application.

When I'm running my rspec tests, i get the following Deprecation Warning:
`DEPRECATION WARNING: env is deprecated and will be removed from Rails 5.1. (called from integrate_with_devise_trackable! at /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/simple_token_authentication-090ad57392b0/lib/simple_token_authentication/sign_in_handler.rb:16)`

**Comment by fighterii** [comment]
[This commit](https://github.com/rails/rails/commit/05934d24aff62d66fc62621aa38dae6456e276be) is the deprecation, and as stated [here](https://github.com/rails/rails/issues/23294), you have to use `request.env` instead.

But only changing this line 16 in sign_in_handler.rb, will cause the tests of simple_token_authentication to fail, (as you can see in [PR #238](https://github.com/gonzalo-bulnes/simple_token_authentication/pull/238). But my app is still working correctly with this change and all tests are passing without deprecation warnings.

**Comment by gonzalo-bulnes** [comment]
Great, thank you @fighterii, I missed that one, and you're totally right. I'll include your fix in the experimental branch tonight.

**Comment by gonzalo-bulnes** [comment]
@fighterii I updated the experimental branch with your fix.

Note that, as a rule of thumb, you need to make sure that the `Gemfile.lock` is always committed along with any `Gemfile` (or `*.gemspec`) changes. It's the same idea as always committing the resulting `db/schema.rb` along with any new migration.

See also #214
