### ISSUE TITLE
fallback: :exception causes error when devise_for is namespaced

### ISSUE THREAD

**Issue by ntippie** [gonzalo-bulnes/simple_token_authentication#247]
When `devise_for` in `routes.rb` is namespaced, the devise helpers receive a prefix. For example, in the excerpt below, the devise helper methods will be named ` authenticate_api_role ` and ` current_api_role `. However, it seems that simple_token_authentication's `Entity` class does not correctly infer the helper method names. Authentication does seem to function correctly in every tested scenario.

I am unsure of the behavior for `fallback: devise` (the default behavior) as I am working with an API-only application. Additional testing for this is requested.

` undefined method 'current_role' for #<Api::V1::AccountsController:0x00560ab4e80ae8> `
`simple_token_authentication (1.13.0) lib/simple_token_authentication/exception_fallback_handler.rb:8:in 'fallback!' `

```
    # Does result in an HTTP 401 response in a Devise context.
    def fallback!(controller, entity)
      throw(:warden, scope: entity.name_underscore.to_sym) if controller.send("current_#{entity.name_underscore}").nil?
    end
  end
end
```

Here is the excerpt from my routes.rb:

```
namespace :api, defaults: { format: :json }, constraints: SubdomainConstraints.new(subdomain: 'api'), path: '/' do
    scope module: :v1,
      constraints: ApiConstraints.new(version: 1, default: true) do

      devise_for :users, skip: :sessions
      devise_for :roles, skip: :sessions
```

And from the controller:
```
class Api::RoleAuthController < ApplicationController
  acts_as_token_authentication_handler_for Role, as: :role, fallback: :exception
```

There's an easy workaround done by specifying the `singular` option for `devise_for`, which will be used to create all helper methods:
```
      devise_for :users, skip: :sessions, singular: :user
      devise_for :roles, skip: :sessions, singular: :role
```

I believe that the proper approach would be to parse these from `Devise.mappings`, but as a relatively new Ruby/Rails user I would prefer to receive some guidance on the implementation strategy before submitting a PR.

**Comment by gonzalo-bulnes** [comment]
Hello @ntippie,

Please see #83. Using the **alias** option was a good idea. However, `role` is the default name for the `Role` class, and:

``` ruby
acts_as_token_authentication_handler_for Role, as: :role

# is strictly equivalent to:
acts_as_token_authentication_handler_for Role
```

Try:

```ruby
acts_as_token_authentication_handler_for Role, as: :api_role # and any other options you need
```

Regards!
