### ISSUE TITLE
DEPRECATION WARNING: Module#qualified_const_defined?

### ISSUE THREAD

**Issue by lekishvili** [gonzalo-bulnes/simple_token_authentication#253]
Deprecation warning on Rails 5.0.0.rc1

`DEPRECATION WARNING: Module#qualified_const_defined? is deprecated in favour of the builtin Module#const_defined? and will be removed in Rails 5.1. (called from adapter_dependency_fulfilled? at /home/acid/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/simple_token_authentication-7cca58547417/lib/simple_token_authentication.rb:49)
`

**Comment by gonzalo-bulnes** [comment]
Hi @lekishvili, see #214.
