### ISSUE TITLE
sign_in response is empty

### ISSUE THREAD

**Issue by adrianodennanni** [gonzalo-bulnes/simple_token_authentication#257]
Using Rails 5.0.0.rc1 api-only.

Hello!
When I perform a POST sign in like this:
`{"user":{"email":"test@net.map","password":"12345678"}}`

I end up receiving an empty response. If I write a wrong login, the response is (as it should be):
`Invalid Email or password.`

Is this a known issue?

In advance, thanks for the help.

**Comment by gonzalo-bulnes** [comment]
Hello @adrianodennanni,

At first sight, nothing indicates that this is this related to token authentication - so I guess that something is missing ; )

Please see the **[Asking for help](https://github.com/gonzalo-bulnes/simple_token_authentication/wiki/Asking-for-help)** section of the wiki for guidelines about gathering the relevant information to troubleshoot your token authentication setup.

**Comment by adrianodennanni** [comment]
The problem was with Rails API and default response not being in JSON

My changes were:

**ApplicationControler :**
`class ApplicationController < ActionController::API
  respond_to :json
end`

**Routes.rb :**
`devise_for :users, defaults: {format: :json}`

Sorry for the inconvenience

**Comment by gonzalo-bulnes** [comment]
I'm glad you found the cause of your issue, thank you for your feedback @adrianodennanni!
