### ISSUE TITLE
undefined local variable or method `acts_as_token_authenticatable'

### ISSUE THREAD

**Issue by kavita-chitnis** [gonzalo-bulnes/simple_token_authentication#258]
Hi,
I installed the Gem and did the configuration as mentioned. But I get the following error on User model
undefined local variable or method `acts_as_token_authenticatable'

Gem File->
gem 'rails','3.2.21'
gem 'devise'
gem 'devise_security_extension', :git => 'https://github.com/frugardc/devise_security_extension.git'
gem 'devise_invitable', '~> 1.5.2'
gem 'simple_token_authentication'

User Model ->
class User < ActiveRecord::Base
   acts_as_token_authenticatable
  
  devise :invitable, :database_authenticatable, :registerable,:password_expirable, :secure_validatable,
         :recoverable, :rememberable, :trackable, :confirmable, :lockable, :timeoutable

**Comment by gonzalo-bulnes** [comment]
Hello @kavita-chitnis,

What version of _Simple Token Authentication_ are you using? (See the **[Asking for help][wiki]** section of the wiki for more details about relevant troubleshooting information.)

In a Rails application, models get the ability to _act as token authenticatable_ quite automatically, did you install the bundle (`bundle install`)? Does `require 'simple_token_authentication'` in your model help?

  [wiki]: https://github.com/gonzalo-bulnes/simple_token_authentication/wiki/Asking-for-help

**Comment by kavita-chitnis** [comment]
Hi, I had added just gem 'simple_token_authentication', '~> 1.0' to the gemfile. When I changed it to 
gem 'simple_token_authentication', '~> 1.0' as mentioned in the configuration guide, everything worked perfect!
Sorry about the false alarm and thank you for your help and such a perfect Gem!

**Comment by azmat-ali-9** [comment]
For newbies like me, just restart your server ❤️
