### ISSUE TITLE
undefined method 'generate_token' with devise_inviteable

### ISSUE THREAD

**Issue by hsson** [gonzalo-bulnes/simple_token_authentication#259]
I am currently trying to integrate this in an existing application which uses devise_inviteable for inviting users over email. I thought everything was working until I tried actually inviting a new user (everything else works). First, when trying to create a user the ```user.valid?``` gives an error saying password can't be blank, and then when trying to manually invite a user without validation using ```user.invite!``` I get the error
```
undefined method `generate_token' for #<Class:0x00564023407220>
```
Any ideas on how to fix this? If I can't get this to work I won't be able to use this gem but I really want to.

**Comment by gonzalo-bulnes** [comment]
Hello @hsson,

The user validation error related to the password being blank seems to be a common issue when using the inviteable strategy, I'm sure that details about that can be found in their documentation.

The `undefined method: generate_token` looks stranger, do you have more context on it? Can you determine actually what class is `#<Class:0x00564023407220>`? (Part of the error trace may be relevant.)

**Comment by hsson** [comment]
Hello, thanks for the fast response!

Yes it certainly looks that way, I'll look into it! And the genreate_token error was also caused by the devise_invitable gem. So after some more research it seems there is nothing wrong with your gem :smile: The problem occured since I needed to update devise and devise_invitable when installing this gem and a bug from devise_invitable slipped in. You can probably close this issue since it isn't very related to this gem after all :+1: 

Really like the simplicity of this gem btw! Keep it up :+1:
