### ISSUE TITLE
[Question]: How to regenerate the token and how to inform the user about the token

### ISSUE THREAD

**Issue by kavita-chitnis** [gonzalo-bulnes/simple_token_authentication#260]
Hi, I just had a couple of questions regarding this Gem

1: How do we inform the user about his token?
  Is this done outside of this gem i.e. just email the user his token
2: Does this token ever expire?
3: How can a token be regenerated? 
Manipulating the DB is one way but is there any other?

**Comment by gonzalo-bulnes** [comment]
A quick review of the [FAQ](https://github.com/gonzalo-bulnes/simple_token_authentication/issues?q=is%3Aissue+label%3Aquestion+is%3Aclosed) gives you: #156, #52.
