### ISSUE TITLE
Adding `acts_as_token_authentication_handler_for User` makes all controllers in my app require authentication

### ISSUE THREAD

**Issue by markbao** [gonzalo-bulnes/simple_token_authentication#264]
Hi there,

I'm seeing an issue where adding `acts_as_token_authentication_handler_for User` to my `application_controller.rb` as suggested in the README makes all of the controllers in my app require authentication. This means that all of my controllers redirect to the sign in page if a session isn't available. This doesn't seem like the expected behavior, but perhaps I'm misunderstanding what that statement does. Should I only be adding that line to controllers that require authentication? What if I need to exclude pages in a controller – do I use `unless`?

Thanks!

**Comment by gonzalo-bulnes** [comment]
Hello @markbao,

Include `acts_as_token_authentication_handler_for User` in all the controllers that need to be able to authenticate users through token authentication.

Note that what makes some kind of authentication required is falling back to other Devise authentication strategies when token authentication fails. Falling back to Devise is the default behaviour, but you can opt for not doing it by setting the **fallback** option to `false` (token authentication is not required) or `exception` (token authentication is required). (There are more details about that in the `README`.)

If for some reason you want or don't want some controller actions to support token authentication, then you can filter them using `if` or `unless`. (You'll find more about that searching for "conditional authentication" in the closed issues that are labelled as "question".)

Does all that make sense?

**Comment by gonzalo-bulnes** [comment]
And yes, the examples are written using `ApplicationController` as an example only, any controller will do.

**Comment by markbao** [comment]
@gonzalo-bulnes Thank you for your detailed explanation, that makes sense! Now, if I wanted to enable token authentication on select controllers *and* my `Users` controllers (provided by Devise), would I need to override the Devise controllers in some way? Sorry for the basic question!

**Comment by gonzalo-bulnes** [comment]
Yes, I think so.

Out of the box, all the controllers that inherit from `ActiveController::Base` (i.e. all your controllers) are able to act as token authentication handlers, but none on them does it until you explicitly declare that it  `acts_as_token...`.

If you want to add that declaration in a controller that you didn't write, you can either perform the enablement in one of its parent classes (hence the examples with `ApplicationController`) or re-open ("override") the class to do it.

(Don't be sorry, you're welcome!)

**Comment by markbao** [comment]
This solved my issue and I understand the gem better now. Thank you! :)
