### ISSUE TITLE
Overriding invalid authentication 

### ISSUE THREAD

**Issue by krazedkrish** [gonzalo-bulnes/simple_token_authentication#265]
How can override the error message for invalid authentication, when the email address, or authentication token is mistaken.

for now it is returning 401 with emtpy error.

I would like to replace it with something like this.
render json: { error: "Authentication error", code: 1 }, status: 401

**Comment by gonzalo-bulnes** [comment]
Hello @krazedkrish, please see #201 so we can keep all the conversations related to this issue in a single place : )

**Comment by krazedkrish** [comment]
thanks @gonzalo-bulnes
