### ISSUE TITLE
Concurrent sign_in and sign_out

### ISSUE THREAD

**Issue by ysyyork** [gonzalo-bulnes/simple_token_authentication#270]
Hi, 

I have a use case that one account is shared by many client devices, e.g. 10 devices can simultaneously sign in. With sign in, it if fine. But with sign out, once any device sign out, the token will change. Then other devices will be automatically sign out. But what I want to is to keep other devices still signed in. How can I do that? Thanks.

**Comment by gonzalo-bulnes** [comment]
Hello @ysyyork! I believe https://github.com/gonzalo-bulnes/simple_token_authentication/issues/135 answers to your question. : )

**Comment by ysyyork** [comment]
@gonzalo-bulnes Thanks, this is very helpful. I solved it using Tiddle
