### ISSUE TITLE
API authentication (how the user gets his token in the first place)

### ISSUE THREAD

**Issue by brunofacca** [gonzalo-bulnes/simple_token_authentication#276]
I'd like the client to send a request including his credentials (e.g., e-mail and password) and the API responds with the corresponding token (which will be used to authenticate all following API requests).  In other words, I need a way to let the client know its token so the tokens can be reset periodically without locking the clients out.  Is there a built-in way to do that? If not, can you suggest an effective approach?

Thank you.

**Comment by gonzalo-bulnes** [comment]
Hello @brunofacca,

The requests involving the user password are handled by Devise (they correspond to the _database_authenticatable_ strategy). What you need to do is including the user's _authentication_token_ in the response that Devise composes. Once that done, your API client must store the token and use it to perform the subsequent requests, which will be handled by Simple Token Authentication.

You'll likely find how to do the first part in the Devise documentation ([wiki](https://github.com/plataformatec/devise/wiki) maybe?). The second half can be achieved either including [query params or HTTP headers](https://github.com/gonzalo-bulnes/simple_token_authentication/tree/v1.14.0#authentication-method-1-query-params) in the subsequent requests.

Regards!

**Comment by brunofacca** [comment]
Hello @gonzalo-bulnes,

Thank you for the quick and detailed reply.

Regards
