### ISSUE TITLE
Login with username or email?

### ISSUE THREAD

**Issue by qx** [gonzalo-bulnes/simple_token_authentication#283]
I've found hours,but there is no example or read me how to implement it?
```
  {entity: {authentication_token: 'X-User-Token', login: 'X-User-Login'}}
  config.header_names = {user: {authentication_token: 'X-User-Token', login: 'X-User-Login'}}
  config.identifiers = {user: 'login'}
```
get errors  undefine column login in users
I have done
[devise login in with email or username](https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address#tell-devise-to-use-username-in-the-authentication_keys),and work as well in web page. fails in simple_token_authentication
Login with username _**or**_ email,How do it?

**Comment by qx** [comment]
overwrite  

```
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", {:value => login.downcase}]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
```
```
  def self.find_for_authentication(warden_conditions)
    self.find_for_database_authentication(warden_conditions)
  end
```

fixed

**Comment by Montaguti** [comment]
Where did you overwrite that? Which file?
