### ISSUE TITLE
Updated, easily accessible, example Devise controllers

### ISSUE THREAD

**Issue by TrevorHinesley** [gonzalo-bulnes/simple_token_authentication#289]
I know there have been links to Gists over the last couple years, scattered throughout different issues, of example controllers which override Devise's default controllers to make use of this gem and JSON requests, but are there any up-to-date versions? 

It would be nice if there was a section of the Wiki showing this as well. It would allow people to get up and running quickly.

**Comment by gonzalo-bulnes** [comment]
Hi @TrevorHinesley,

I agree with that, and have made a call for feedback and/or contributions in #271 to address the concern. You feedback there is welcome, and please feel also welcome to create new pages in the [wiki][wiki] describing the scenario that you would like to implement. As long as there is a disclaimer if the page is incomplete or needs review, I think it's totally fine to have work in progress or incomplete pages in the wiki.

Also, don't underestimate the value of describing the scenario you're trying to implement: providing missing information if often much easier than describing hypothetical scenarios out of the blue! Do you feel like doing that? : )

  [wiki]: https://github.com/gonzalo-bulnes/simple_token_authentication/wiki

**Comment by gonzalo-bulnes** [comment]
@TrevorHinesley You might be interested in #293!

**Comment by TrevorHinesley** [comment]
Thanks a ton!!
