### ISSUE TITLE
Q: MIT License? A: No. GPL-3.0+ it is.

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [gonzalo-bulnes/simple_token_authentication#304]
Any chance you can release this under MIT license or something that doesn't require full disclosure of source code?

**Comment by gonzalo-bulnes** [comment]
Hi @Fire-Dragon-DoL, I provided more details about the whys-and-why-nots of the GPL in #240 : )

**Comment by Fire-Dragon-DoL** [comment]
@gonzalo-bulnes thanks for the deep explaination! 

Any chance you can consider the LGPL instead? Any fork that gets distributed must be GPL or LGPL, but doesn't force the rest of the codebase under GPL, making this gem usable in commercial products.

I'm interested in using the gem in a commercial product, but I can't use GPL for it

**Comment by gonzalo-bulnes** [comment]
_Thinking..._ :wink:

**Comment by vfonic** [comment]
Just to add my two cents to this open issue:

> Note that the GPL does not regulate how you use the code, nor whether or not you modify it until you distribute your changes.

Yes, it does. Well, "distribute" would basically mean: until you deploy your code. From that point on, your entire codebase should be GPL or GPL-compatible license, meaning you need to disclose the entire codebase publicly.

I'm just unsure why this project would be released under any license different from the original Devise gem? 

> So you can do whatever you want in a private fork for your own usage.

What does "for your own usage" here mean? You can look at the code and add/remove characters, but if you wish to deploy the code, you need to open source your project. Well, that sucks for a lot of people, I'd say. :) 

I'm also concerned that there might be developers who missed this license and just added this gem to their closed-source projects.

**Comment by mferrerisaza** [comment]
@gonzalo-bulnes did you make up your mind regarding the possibility of changing this to something like LGPL in order to be able to use this for commercial products?

Thanks

**Comment by gonzalo-bulnes** [comment]
Hi @mferrerisaza,

Yes. I won't be changing the license. If GPL-3.0+ doesn't fit your purpose, then Simple Token Authentication doesn't fit your purpose.

Thanks for bringing my attention to the fact Si hadn't made that clear, it should be! I'll edit the title of the issue to reflect that. 🙂
