### ISSUE TITLE
Retrive Current User

### ISSUE THREAD

**Issue by oscarsanchez** [gonzalo-bulnes/simple_token_authentication#306]
can I retrieve current_user only with the token ? without the email ?

**Comment by gonzalo-bulnes** [comment]
Hi @oscarsanchez, short answer is "no". Longer answer is: "you shouldn't probably not" and that's the original purpose of the gem. You can find more details in the [gist that inspired the gem](https://gist.github.com/josevalim/fb706b1e933ef01e4fb6) : )
