### ISSUE TITLE
Validate token against certificate

### ISSUE THREAD

**Issue by vlkrrrr** [gonzalo-bulnes/simple_token_authentication#307]
Is ist possible to configure a token validation against a certificate? The tokens will be generate by a private key and simple_token_authentication should validate them against the public key. If they are valid, the user gets access.

**Comment by gonzalo-bulnes** [comment]
Hello @volkit,

No, and I think it would go beyond the scope of _simple_ token authentication :wink: 
You may be interested in [JWT](https://jwt.io/) though!
