### ISSUE TITLE
Mongoid does support Rails 6 now/soon

### ISSUE THREAD

**Issue by unused** [gonzalo-bulnes/simple_token_authentication#351]
> As far as I know Mongoid doesn't support Rails 6
> Please let me know if this isn't true when you read it!

Just leaving a note as I stumbled on [your comment](https://github.com/gonzalo-bulnes/simple_token_authentication/blob/master/lib/simple_token_authentication/adapters/mongoid_adapter.rb#L4), although the [mongoid rails 6 support](https://github.com/mongodb/mongoid/pull/4652) is not yet published in the latest gem release. :wave:

**Comment by gonzalo-bulnes** [comment]
Hi @unused!

Thank you for the note! If you happen to know when/what would be needed to bring Mongoid / Rails 6 in, please let me know, I don't follow Mongoid updates closely and I'd appreciate any information on this : )

**Comment by p-mongo** [comment]
Mongoid 7.0.5 has just been released with Rails 6 support.

**Comment by unused** [comment]
Thanks a lot @p-mongo for notifying - that's great to hear :tada: 

I'll have a look asap and update the PR on demand.
