### ISSUE TITLE
uninitialized constant SimpleTokenAuthentication::Adapters

### ISSUE THREAD

**Issue by mberbero** [gonzalo-bulnes/simple_token_authentication#352]
![image](https://user-images.githubusercontent.com/40326463/64907589-3e315080-d6fd-11e9-8093-7e3b89b82a9b.png)
![image](https://user-images.githubusercontent.com/40326463/64907598-50ab8a00-d6fd-11e9-96fd-baab7a12d66d.png)

**Comment by gonzalo-bulnes** [comment]
Hello @mberbero,

Does this still happen when you're not using Mongoid?

**Why am I asking this?**

- Mongoid is not currently supported under Rails 6 ([more on this](https://github.com/gonzalo-bulnes/simple_token_authentication/pull/350), [contributions welcome!](https://github.com/gonzalo-bulnes/simple_token_authentication/issues/351))
- I believe should have added a guard to prevent the adapter from being loaded when using an unsupported combination of Mongoid and Rails ([example of such a guard currently in use for other adapters](https://github.com/gonzalo-bulnes/simple_token_authentication/blob/v1.16.0/lib/simple_token_authentication.rb#L36))

If you feel like it, adding such a guard would be a appreciated contibution!

**Comment by unused** [comment]
Mongoid has not yet published a release [that contains the PR to support rails 6.0](https://github.com/mongodb/mongoid/compare/v7.0.4...master). I'm happy to send a PR if they do and it does not break anything ;)

**Comment by unused** [comment]
@mberbero [I've been testing](https://github.com/unused/simple_token_authentication/commit/3b676f5a3b0520ee42bcd7dd6360ffc6b25c0bc3) it with rails 6.0 and mongoid#master, I did not figure out any problems yet I probably will not send it to production for any application until a stable mongoid release is provided.

**Comment by gonzalo-bulnes** [comment]
That would be amazing @unused! Please do, and don't hesitate to open it early on and ping me if you need help with anything : )

**Comment by gonzalo-bulnes** [comment]
@mberbero Simple Token Authentication **v1.17.0** supports Mongoid with Rails 6! :confetti_ball: 

The credit goes to @unused who kept track of the corresponding Mongoid release and made the necessary changes. : )
