### ISSUE TITLE
How to protect the registrations controller through token authentication?

### ISSUE THREAD

**Issue by JoshuaNovak919** [gonzalo-bulnes/simple_token_authentication#36]
I am trying to override the registration controller so I can respond with JSON. The issue I am having is that authenticate_scope! is called before [:edit, :update, :destroy] and I need the users to be able to modify their profiles. Is there a good way to handle this with a simple_token_authentication method or something?

**Comment by ryanjm** [comment]
@gonzalo-bulnes Your solution above used to work for me. I'm working on upgrading my project to Rails 4.2.0 and I'm running into an error now. The only thing that has changed is going from version `1.2.0` to `1.7.0`. I don't see a changelog so how would that affect this code?

Here is what the top part of my `RegistrationController` looks like:

```ruby
class Api::RegistrationsController < Devise::RegistrationsController
  prepend_before_filter :require_no_authentication, only: [ :new, :create, :edit, :update, :cancel ]
  prepend_before_filter :authenticate_scope!, only: [:destroy]
  acts_as_token_authentication_handler_for User

  # Disable token authentication for all actions
  # See https://github.com/gonzalo-bulnes/simple_token_authentication/blob/master/lib/simple_token_authentication/acts_as_token_authentication_handler.rb#L12-L15
  skip_before_filter :authenticate_entity_from_token!
  skip_before_filter :authenticate_entity!

  # Enable token authentication only for the :update, :destroy actions
  before_filter :authenticate_entity_from_token!, :only => [:update, :destroy]
  before_filter :authenticate_entity!, :only => [:update, :destroy]
```

My Rspec test:

```ruby
    it "updates attributes of the user" do
      u = create(:user, password: 'helloworld', password_confirmation: 'helloworld')
      binding.pry
      put "/api/users?user_email=#{u.email}&user_token=#{u.authentication_token}", user: { name: "Bob" }
      ...
    end
```

Without the `binding.pry` I get:

```
  1) Api::RegistrationsController update updates attributes of the user
     Failure/Error: put "/api/users?user_email=#{u.email}&user_token=#{u.authentication_token}", user: { name: "Bob" }
     ArgumentError:
       wrong number of arguments (0 for 1)
     # ./spec/requests/api/registrations_controller_spec.rb:32:in `block (3 levels) in <top (required)>'
```

When I stop inside the method and try to run the put myself I get:

```
> put "/api/users?user_email=#{u.email}&user_token=#{u.authentication_token}"
ArgumentError: wrong number of arguments (0 for 1)
from /Users/ryanjm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/simple_token_authentication-1.7.0/lib/simple_token_authentication/token_authentication_handler.rb:29:in `authenticate_entity_from_token!'
```

Any ideas?

**Comment by ryanjm** [comment]
Alright, looking through the readme it looks like my controller should be simplified to:

```
  prepend_before_filter :require_no_authentication, only: [ :new, :create, :edit, :update, :cancel ]
  prepend_before_filter :authenticate_scope!, only: [:destroy]
  acts_as_token_authentication_handler_for User, only: [:update, :destroy]
```

Which works. I just have to ensure there is a current user before trying to do anything else. It doesn't throw an error like I was expecting... is that correct? I thought it threw an error when the user wasn't valid before.

**Comment by ryanjm** [comment]
Alright, for others running into this, I fixed it by adding this to my application controller:

```ruby
  acts_as_token_authentication_handler_for User, fallback_to_devise: false
  before_filter :validate_user

  def validate_user
    user_signed_in? || throw(:warden, scope: :user)
  end
```

This comes from this [method](https://github.com/donbobka/simple_token_authentication/blob/40db748e9e1ac8a9b206425594b273f37fbf7594/lib/simple_token_authentication/acts_as_token_authentication_handler.rb#L20-L23) via @gonzalo-bulnes's [comment](https://github.com/gonzalo-bulnes/simple_token_authentication/issues/67#issuecomment-45567362).

Then in the `RegistrationController` I have:

```ruby
  prepend_before_filter :require_no_authentication, only: [ :new, :create, :edit, :update, :cancel ]
  prepend_before_filter :authenticate_scope!, only: [:destroy]
  acts_as_token_authentication_handler_for User, only: [:update, :destroy]
  skip_before_filter :validate_user, only: [:create]
```

Hopefully this helps someone else.

**Comment by gonzalo-bulnes** [comment]
Hi @ryanjm,

First of all, thanks for your comments.


**1. About the controllers behaviour when authentication fails** (see [those][problem] [two][solution] comments)

> It just doesn't throw the 401 I'm expecting when the user isn't found. But looking through the code for this gem, I'm not sure if that is what I should be expecting.

The core feature of the gem is providing an authentication mecanism, that's to say authenticating users when credentials (authentication token, identifier) are present. Beyond that, defining the controllers behaviour when authentication fails is IMO, out of scope. That can be discussed, and I find the @donbobka iniciative absolutely well founded. Besides, that's the way to go to ensure controllers do respond with the expected 401 HTTP errors, and the example you provided is both correct and helpful.

  [problem]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/36#issuecomment-72337773
  [solution]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/36#issuecomment-72339744

**2. About the failing spec example** (see [this comment][spec])

Yes, an idea: you should never call `authenticate_entity_from_token!` (nor any "entity" method, those are [private methods][private]).
Let's say your controller _handles token authentication for `User`_. Then [two methods are defined automatically][define]: `authenticate_user_from_token` and `authenticate_user_from_token!`. Depending on the value of the _fallback_ option, one, or the other, is [set as a callback][hook].

It's that method that you should use when skipping or setting different callbacks (filters). In your example it would be the bang `!` one, `authenticate_user_from:token!`. (Note that it takes no arguments, while private methods do.)

  [spec]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/36#issuecomment-72336295
  [private]: https://github.com/gonzalo-bulnes/simple_token_authentication/blob/master/lib/simple_token_authentication/token_authentication_handler.rb#L19-L20
  [define]: https://github.com/gonzalo-bulnes/simple_token_authentication/blob/master/lib/simple_token_authentication/token_authentication_handler.rb#L97
  [hook]: https://github.com/gonzalo-bulnes/simple_token_authentication/blob/master/lib/simple_token_authentication/token_authentication_handler.rb#L98

**Comment by gonzalo-bulnes** [comment]
**3. About the `only`, `except` options**

Yours was a good move. Those options were included to avoid the `skip`ing then setting again the callbacks to scope them. In fact, the second point of my previous comment may be much less useful that it was, but I think it's always good to know how things do work ; )

Regards!
