### ISSUE TITLE
Where should I store the token on the frontend?

### ISSUE THREAD

**Issue by imgyf** [gonzalo-bulnes/simple_token_authentication#362]
Hey @gonzalo-bulnes, I love your super simple gem for API authentication.

I'm wondering what's the most secure way to store the token on the frontend. Could you advise, please? Thanks.

**Comment by swikars1** [comment]
localstorage, your can encrypt before storing if u want

**Comment by buncis** [comment]
@gohyifan check this https://pragmaticstudio.com/tutorials/rails-session-cookies-for-api-authentication

as for localstorage its kinda dangerous because its vulnerable to XSS attack

**Comment by gonzalo-bulnes** [comment]
@imgyf Indeed, the short answer is that you should probably not store these tokens on the frontend. I've added a [note about this in the README](https://github.com/gonzalo-bulnes/simple_token_authentication#security-notice).

Thanks for the helpful reference @buncis !
