### ISSUE TITLE
Getting an ActionController::InvalidAuthenticityToken exception? (R: Take a look at CSRF answers!)

### ISSUE THREAD

**Issue by amalagaura** [gonzalo-bulnes/simple_token_authentication#37]
I am having the strangest issue. I am only having successful authentications on GET's. I am passing the email and token via headers, not params: `X-User-Email` It works on GET, but not on PUT or PATCH.

When I run a debugger it goes to the `authenticate_entity_from_token!` method _only_ on GET. But on a PATH or PUT I get a `ActionController::InvalidAuthenticityToken`
 and it does not go to the `authenticate_entity_from_token!` method.

My routes are regular REST resources. It is a simple Rails 4 app with a single model just for testing.

**Comment by reisner** [comment]
Should this be mentioned in the installation steps for this gem?
