### ISSUE TITLE
Getting a NameError - undefined method `authenticate_user!'? (R: Check the token authenticatable model name.)

### ISSUE THREAD

**Issue by JeskTop** [gonzalo-bulnes/simple_token_authentication#42]
Why I set `acts_as_token_authentication_handler_for User` to my ApplicationController, I will have the problem is `NameError - undefined method`authenticate_user!'`. I am the reference document, but also has this problem, I don't know what is happen.

**Comment by amitfriedman12** [comment]
I added this line to my controller which did the trick for me:
```
    include Devise::Controllers::Helpers
```

**Comment by gonzalo-bulnes** [comment]
Thank you for sharing @amitfriedman12!

**Comment by erijonhson** [comment]
None of the above works for me.
