### ISSUE TITLE
Any way to skip authentication when you use this?

### ISSUE THREAD

**Issue by walterdavis** [gonzalo-bulnes/simple_token_authentication#84]
I have a single route that I have skipped authentication on in Devise using the except: syntax in the relevant controller. But when I apply this token authentication technique in my Application Controller, that endpoint just shows the "You are being redirected" link instead of the public content. Any tips on this? 

Thanks,

Walter

**Comment by gonzalo-bulnes** [comment]
If you want to skip token authentication depending on a more complex condition, see #155.

**Comment by gonzalo-bulnes** [comment]
In case you have trouble skipping Devise authentication, see also #164.
